#!/usr/bin/env python3
""" Defines 1-async_comprehension.py"""
from typing import List
import asyncio


async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Asynchronous coroutine that uses an asynchronous comprehension
    to collect 10 random numbers generated by the async_generator.
    Returns a list of the collected random numbers.
    """
    return [i async for i in async_generator()]
